services:
  - type: web
    name: portfolio-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npx tsc
    startCommand: node dist/server.js
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromConfig: true
      - key: CLOUDINARY_CLOUD_NAME
        fromConfig: true
      - key: CLOUDINARY_API_KEY
        fromConfig: true
      - key: CLOUDINARY_API_SECRET
        fromConfig: true
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        fromConfig: true
      - key: EMAIL_USER
        fromConfig: true
      - key: EMAIL_PASS
        fromConfig: true
